#!/bin/bash
. ~/.nvm/nvm.sh
. ~/.bashrc
echo "!!!!!!!! Lets deploy on production !!!!!!!!"
cd /var/www/ucom.frontend
git checkout master
git pull
npm ci --ignore-scripts
npm run production
echo "Lets reload pm2 with update env and saving new configuration"
/home/dev/.nvm/versions/node/v10.9.0/bin/pm2 reload ecosystem-production.config.js --update-env
/home/dev/.nvm/versions/node/v10.9.0/bin/pm2 save
echo "!!!!!!!! Deploy on production is finished !!!!!!!!"
