const getInitialState = () => ({
  title: null,
      post_type_id: OFFER_TYPES[0].id,
      action_button_title: null,
      action_button_url: null,
      action_duration_in_days: null,
      time_sale_unlimited: null,
      team_ids: [],
      main_image_filename: null,
      leading_text: null,
      description: null,
      errors: null,
      coverDataUrl: null,
      loaded: this.props.match.params.id === undefined,
      saved: false,
      id: null,
});
