export const SET_ACCOUNT_DATA = 'SETTINGS:SET_ACCOUNT_DATA';
export const RESET_ACCOUNT = 'SETTINGS:RESET_ACCOUNT';
export const VALIDATE_ACCOUNT_FIELD = 'SETTINGS:VALIDATE_ACCOUNT_FIELD';

export const RESET_BLACKLIST = 'SETTINGS:RESET_BLACKLIST';

export const RESET_NOTIFICATIONS = 'SETTINGS:RESET_NOTIFICATIONS';
export const SET_NOTIFICATIONS_DATA = 'SETTINGS:SET_NOTIFICATIONS_DATA';

export const RESET_REFERRAL = 'SETTINGS:RESET_REFERRAL';

export const RESET_SECURITY = 'SETTINGS:RESET_SECURITY';
export const SET_SECURITY_DATA = 'SETTINGS:SET_SECURITY_DATA';
