export const SET_USER = 'USER:SET_USER';
export const REMOVE_USER = 'USER:REMOVE_USER';

export const EDIT_USER = 'USER:EDIT_USER';
export const EDIT_USER_COMPLETED = 'USER:EDIT_USER_COMPLETED';
export const EDIT_USER_FAIL = 'USER:EDIT_USER_FAIL';

export const EDIT_GENERAL_INFO = 'USER:EDIT_GENERAL_INFO';
export const EDIT_GENERAL_INFO_COMPLETED = 'USER:EDIT_GENERAL_INFO_COMPLETED';
export const EDIT_GENERAL_INFO_FAIL = 'USER:EDIT_GENERAL_INFO_FAIL';

export const EDIT_WORK_AND_EDUCATION = 'USER:EDIT_WORK_AND_EDUCATION';
export const EDIT_WORK_AND_EDUCATION_COMPLETED = 'USER:EDIT_WORK_AND_EDUCATION_COMPLETED';
export const EDIT_WORK_AND_EDUCATION_FAIL = 'USER:EDIT_WORK_AND_EDUCATION_FAIL';

export const EDIT_CONTACTS = 'USER:EDIT_CONTACTS';
export const EDIT_CONTACTS_COMPLETED = 'USER:EDIT_CONTACTS_COMPLETED';
export const EDIT_CONTACTS_FAIL = 'USER:EDIT_CONTACTS_FAIL';

export const UPLOAD_AVATAR = 'USER:UPLOAD_AVATAR';
export const UPLOAD_AVATAR_COMPLETED = 'USER:UPLOAD_AVATAR_COMPLETED';
export const UPLOAD_AVATAR_FAIL = 'USER:UPLOAD_AVATAR_FAIL';
