export function convertServerUser(response) {
  return {
    id: response.id,
    accountName: response.account_name,
    nickName: response.nickname,
    firstName: response.first_name,
    lastName: response.last_name,
    email: response.email,
    phoneNumber: response.phone_number,
    birthday: response.birthday,
    about: response.about,
    country: response.country,
    city: response.city,
    address: response.address,
    moodMessage: response.mood_message,
    avatarFileName: response.avatar_filename,
    privateKey: response.private_key,
    publicKey: response.public_key,
    ownerPublicKey: response.owner_public_key,
    currencyToShow: response.currency_to_show,
    firstCurrency: response.first_currency,
    firstCurrencyYear: response.first_currency_year,
    personalWebsiteUrl: response.personal_website_url,
    achievementsFileName: response.achievements_filename,
    currentRate: response.current_rate,
    blockchainRegistrationStatus: response.blockchain_registration_status,
    createdAt: response.created_at,
    updatedAt: response.updated_at,
    usersEducation: response.users_education,
    usersJobs: response.users_jobs,
    usersSources: response.users_sources,
    iFollow: response.I_follow,
    followedBy: response.followed_by,
  };
}

export function convertClientUser(userData) {
  return {
    id: userData.id,
    account_name: userData.accountName,
    nickname: userData.nickName,
    first_name: userData.firstName,
    last_name: userData.lastName,
    email: userData.email,
    phone_number: userData.phoneNumber,
    birthday: userData.birthday,
    about: userData.about,
    country: userData.country,
    city: userData.city,
    address: userData.address,
    mood_message: userData.moodMessage,
    avatar_filename: userData.avatarFileName,
    private_key: userData.privateKey,
    public_key: userData.publicKey,
    owner_public_key: userData.ownerPublicKey,
    currency_to_show: userData.currencyToShow,
    first_currency: userData.firstCurrency,
    first_currency_year: userData.firstCurrencyYear,
    personal_website_url: userData.personalWebsiteUrl,
    achievements_filename: userData.achievementsFileName,
    current_rate: userData.currentRate,
    blockchain_registration_status: userData.blockchainRegistrationStatus,
    created_at: userData.createdAt,
    updated_at: userData.updatedAt,
    users_education: userData.usersEducation,
    users_jobs: userData.usersJobs,
    users_sources: userData.usersSources,
    I_follow: userData.iFollow,
    followed_by: userData.followedBy,
  };
}
